openapi: "3.0.0"
info:
  version: 1.0.0
  title: Carts
  license:
    name: MIT
servers:
  - url: http://localhost:8080/api
paths:
  /products:
    get:
      summary: List all products
      operationId: listProducts
      tags:
        - products
      responses:
        '200':
          description: A paged array of products
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Products"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /products/{productId}:
    get:
      summary: Info for a specific product
      operationId: showProductById
      tags:
        - product
      parameters:
        - name: productId
          in: path
          required: true
          description: The id of the product to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /cart:
    post:
      summary: New cart
      operationId: newCart
      tags:
        - cart
      responses:
        '200':
          description: The id of a new empty cart
          content:
            application/json:
              schema:
                type: integer
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                type: integer
  /cart/{userId}:
    get:
      summary: List the cart
      operationId: listCart
      tags:
        - cart
      parameters:
        - name: userId
          in: path
          required: true
          description: The cart id
          schema:
            type: string
      responses:
        '200':
          description: A paged array of items
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: checkout, delete the cart from the server
      operationId: checkoutCart
      tags:
        - cart
      parameters:
        - name: userId
          in: path
          required: true
          description: The cart id
          schema:
            type: string
      responses:
        '200':
          description: A paged array of items
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /cart/{userId}/{productId}:
    delete:
      summary: Remove the product from the cart
      operationId: removeFromCart
      tags:
        - cart
      parameters:
        - name: userId
          in: path
          required: true
          description: The cart id
          schema:
            type: string
        - name: productId
          in: path
          required: true
          description: The id of the product to add
          schema:
            type: string
      responses:
        '200':
          description: A paged array of items
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /cart/{userId}/{productId}/{amount}:
    post:
      summary: Add product(s) to the cart
      operationId: addToCart
      tags:
        - cart
      parameters:
        - name: userId
          in: path
          required: true
          description: The cart id
          schema:
            type: string
        - name: productId
          in: path
          required: true
          description: The id of the product to add
          schema:
            type: string
        - name: amount
          in: path
          required: true
          description: The amount of the product to add
          schema:
            type: integer
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /order/checkout:
    post:
      summary: checkout a list of items
      operationId: checkout
      tags:
        - order
      requestBody:
        description: the list of items
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cart"
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: integer
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Product:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number
          format: double
        image:
          type: string
    Products:
      type: array
      items:
        $ref: "#/components/schemas/Product"
    Item:
      type: object
      required:
        - productId
      properties:
        productId:
          type: string
        quantity:
          type: integer
    Cart:
      type: array
      items:
        $ref: "#/components/schemas/Item"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
