server:
  port: 8084

spring:
  application:
    name: pos-delivery
  cloud:
    function:
      definition: cartDeliver
    stream:
      function:
        bindings:
          cartDeliver-in-0: CartDeliverer
      bindings:
        order-approved:
          destination: cart-approved
      rabbit:
        bindings:
          output:
            consumer:
              declare-exchange: false